spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      database: tsensor
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG